// Define action types here

export const FETCHED_ALL_VIDEOS = "FETCHED_ALL_VIDEOS";
export const FETCHED_PROFILE = "FETCHED_PROFILE";
export const SET_LIKED_ERROR = "SET_LIKED_ERROR";
export const SET_WATCHHISTORY_ERROR = "SET_WATCHHISTORY_ERROR";
export const SET_UPLOADEDVIDEOS_ERROR = "SET_UPLOADEDVIDEOS_ERROR";
export const UPDATE_WATCH_HISTORY = "UPDATE_WATCH_HISTORY";
export const CURRENT_USER_AVATAR = "CURRENT_USER_AVATAR";
export const SET_SUBSCRIBER_COUNT = "SET_SUBSCRIBER_COUNT";
export const SET_USER_SUBSCRIBE= "SET_USER_SUBSCRIBE";
export const SET_IS_SUBSCRIBE= "SET_IS_SUBSCRIBE";
export const UPDATE_UPLOADED_VIDEOS= "UPDATE_UPLOADED_VIDEOS";
export const UPDATE_WATCHLATER_VIDEOS= "UPDATE_WATCHLATER_VIDEOS";
export const UPDATE_COMMENT_REPLY= "UPDATE_COMMENT_REPLY";

